GET http://localhost:3000/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzYyMTAwODgwLCJleHAiOjE3NjIxODcyODB9.rvjoTvhFWep1Dn2dBEYAlAc6jzZAGFt0k2jEXcau-7s

###

POST http://localhost:3000/register
content-type: application/json

{
    "username": "admin",
    "email": "admin@gmail.com",
    "password": "admin111",
    "confPass": "admin111"
}
###
POST http://localhost:3000/register
content-type: application/json

{
    "username": "kingmrx",
    "email": "kingmrx@gmail.com",
    "password": "kingmrx111",
    "confPass": "kingmrx111"
}


###
POST http://localhost:3000/login
content-type: application/json

{
    "userOREmail": "kingmrx@gmail.com",
    "password": "kingmrx111"
}
###
POST http://localhost:3000/login
content-type: application/json

{
    "userOREmail": "admin@gmail.com",
    "password": "admin111"
}

###

GET http://localhost:3000/Me
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJraW5nbXJ4IiwiZW1haWwiOiJraW5nbXJ4QGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VycyIsImlhdCI6MTc2MjEwMDQxMCwiZXhwIjoxNzYyMTg2ODEwfQ.wtx92xM1XDC-Sol7KbUjZlLpZGOnmhwlRYnXiOURPvE